[package]
name = "passmgr"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies.rusqlite]
version = "0.26.0"
features = ["bundled"]

[dependencies]
sha2 = "0.10.1"
dialoguer = "0.10.0"

